name: "Build Android App"

on:
  workflow_dispatch:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run NPM Install
        run: npm i

      - name: Build application
        run: |
             cd ./android
             ./gradlew assembleRelease 

      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs/apk/app-release.apk
          retention-days: 3
